Setup info display
JordanPhillips-hub/TokenTrax pull request #56
Opened 2023-11-22 18:34 UTC by JordanPhillips-hub

This pull request includes the creation of the navInfoData file as well as the refactoring of the Navbar, CoinInfo and NavInfoDisplay files to setup and finish the NavInfoDisplay.

2023-11-22 22:05 UTC, constantinlisnic commented on app/components/NavBar/CoinInfo.tsx
> +          ) : null}
No need for ternary operator if the second part is null, instead use a short circuit. 

```
{hasProgressBar && (
<ProgressBar />
)}
```

2023-11-22 22:18 UTC, JordanPhillips-hub commented on app/components/NavBar/CoinInfo.tsx
> +          ) : null}
Thanks I will change this.

2023-11-22 22:18 UTC, constantinlisnic requested changes
Good stuff buddy!

Take a look at the comment I left for a minor suggestion to further refine the code.

2023-11-22 22:42 UTC, yoloOnTheBattlefield requested changes

2023-11-22 22:42 UTC, yoloOnTheBattlefield commented on app/components/NavBar/coinInfoData.ts
> +}
this should be in a utils file

2023-11-23 08:53 UTC, constantinlisnic requested changes

2023-11-23 08:53 UTC, constantinlisnic commented on app/utils/generateCoinInfo.ts
> +}
The file name is not relevant to its content. Extract this utility function in its own file `formatMarketCap.ts` inside the utils folder. 

Imagine you have 10 util functions, this file is going to get messy and it will get harder and harder to find what you need.

2023-11-23 08:53 UTC, constantinlisnic commented on app/utils/generateCoinInfo.ts
> +}
Same here, extract in a separate file.

2023-11-23 15:05 UTC, JordanPhillips-hub commented on app/utils/generateCoinInfo.ts
> +}
I think that I misunderstood Cristians comment. Was he saying to move these 2 functions to the utils folder but keep this one generateCoinInfo where it was. It makes sense to me to move these 2 functions but does not make sense to me to move the other one as this is only related to the coin info display and will not be used anywhere else in the project?

2023-11-23 18:52 UTC, constantinlisnic commented on app/utils/generateCoinInfo.ts
> +}
You're right about the `generateCoinInfo` function, if it's not used anywhere else it makes more sense to keep it close to the component where it's used. Up to you whether you keep it in the component or extract it outside, but in the same folder. Personally I would take it out 'cos it;s too long.

2023-11-23 22:54 UTC, JordanPhillips-hub commented on app/utils/generateCoinInfo.ts
> +}
I do also think that the generateCoinInfo function is fairly long the original purpose for this was to reduce the repetiveness in the NavInfoDisplay component and make the component a bit easier to read with a map over. I have created a new utils file for number formating and moved the necessary functions to the file. For the generateCoinInfo I removed that function and instead created some optional types for the CoinInfo info component to reduce the amount of props needed shortening up the code in the NavInfoDisplay and getting rid of the long function. Thank you guys for the input and guidance!!

2023-11-24 17:34 UTC, merged